
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: rank-and-file_development
test:
  <<: *default
  database: rank-and-file_test
production:
  <<: *default
  database: rank-and-file_production
